spring:
  profiles:
    active: dev

  messages:
    basename: errors

management:
  endpoints:
    web:
      exposure:
        include: 'metrics,health,info,prometheus'

  endpoint:
    health:
      show-details: always # 상세한 헬스 정보 표시

