drop table if exists notice CASCADE;
create table notice
(
    id bigint generated by default as identity,
    title varchar(200),
    content text,
    notice_date varchar(10),
    primary key (id)
);

drop table if exists weather CASCADE;
create table WEATHER(
    fcst_date varchar(8),
    fcst_time varchar(4),
    tmp int,
    sky int,
    pty int,
    primary key (fcst_date, fcst_time)
);

drop table if exists Weather_EXTREMES CASCADE;
create table Weather_EXTREMES(
    fcst_date varchar(8),
    tmn float,
    tmx float,
    primary key (fcst_date)
);

drop table if exists Lifestyle CASCADE;
create table Lifestyle(
    lifestyle_id bigint generated by default as identity,
    bed_time int,
    wakeup_time int,
    sleep_habit int,
    cleaning int,
    aircon int,
    heater int,
    noise int,
    smoking int,
    scent int,
    eating int,
    relationship int,
    home int,
    drinking int,
    age int,
    dorm_hour int,
    primary key (lifestyle_id)
);


drop table if exists Member CASCADE;
create table Member (
    member_id VARCHAR(16),
    lifestyle_id BIGINT,
    dorm VARCHAR(10),
    nickname VARCHAR(20),
    introduce TEXT,
    img VARCHAR(50),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 현재 시간을 기본값으로 설정
    PRIMARY KEY (member_id),
    FOREIGN KEY (lifestyle_id) REFERENCES LifeStyle (lifestyle_id)
);


drop table if exists Recommendation CASCADE;
create table Recommendation(
    result_id bigint generated by default as identity,
    member_id_1 varchar(16),
    member_id_2 varchar(16),
    score double,
    primary key (result_id),
    foreign key (member_id_1) references Member(member_id),
    foreign key (member_id_2) references Member(member_id)
);